### ISSUE TITLE
Incorrect calculation for OCR time

### ISSUE THREAD

**Issue by StephanMayer** [TungstenTransformation/MicrosoftOCR#32]
https://github.com/KofaxTransformation/MicrosoftOCR/blob/5f0fafb7a58fd8e74483b23874a94a002ad8733b/md/Project.vb#L46C50-L46C50

Instead of calculating the value for the XValue field again, change to use pXDoc.TimeOCR here which has been correctly calculated before (including overflow at midnight)

**Comment by TungstenTransformation** [comment]
fixed
