### ISSUE TITLE
get vision ocr 3.2 running on docker on windows and document how to do it

### ISSUE THREAD

**Issue by TungstenRPA** [TungstenTransformation/MicrosoftOCR#40]
docker run --rm -it -p 5001:5000 --memory 10g --cpus 2 mcr.microsoft.com/azure-cognitive-services/vision/read Eula=accept Billing=https://oc-rop.cognitiveservices.azure.com/ ApiKey=......

**Comment by KofaxRPA** [comment]
you need to go to a website to request an API key.

**Comment by TungstenTransformation** [comment]
fixed
